$ bundle --version
Bundler version 1.13.7
gem build 4.gemspec
$ gem push --key github
 \ --host https:
//rubygems.pkg.github.com
/Apetree100122 
 \ 4 1.13.7
gem.metadata = { "github_repo"
 => "ssh:
//github.com
/Apetree100122
/REPOSITORY " * " }
source 
"https://rubygems.org"
 gem
 "rails
" source
 "https://rubygems.pkg.github.com
/Apetree100122" 
do gem "4"
gem 
install
$ bundle --version
Bundler version 1.13.7
