

[ 
{ "id": "/subscriptions/a17f0928-65b4-46da-a104-af9371418db0/resourceGroups/RG1
/providers/Microsoft.Resources/deployments/DeploySqlVmAb-20231122211508/operations/41639C057A2FF670", "operationId": 
"41639C057A2FF670",
"properties": 
{ "provisioningOperation": "Create", "provisioningState": 
"Running", "timestamp": 
"2023-11-23T05:15:53.8001515Z", 
"duration": "PT4.6445059S", "trackingId": "04665ccf-17ee-4437-a242-ff4c0e846a50", 
"statusCode": "OK", "targetResource": 
{ "id": "/subscriptions/a17f0928-65b4-46da-a104-af9371418db0/resourceGroups/RG1/providers/Microsoft.SqlVirtualMachine/
SqlVirtualMachines/SQLServer1", 
"resourceType": "Microsoft.SqlVirtualMachine
/SqlVirtualMachines", "resourceName": "SQLServer1" } } }, { "id": "/
subscriptions/
a17f0928-65b4-46da-a104-af9371418db0/resourceGroups/
RG1/providers/Microsoft.Resources/deployments/DeploySqlVmAb-20231122211508/operations/9BF32365F052F5EC", "operationId": 
"9BF32365F052F5EC",
"properties":
{ "provisioningOperation":
"Action", "provisioningState": 
"Succeeded",
"timestamp": 
"2023-11-23T05:15:49.1298404Z",
"duration": "PT1.6712515S",
"trackingId": "1fa78808-7d03-44df-9517-59178c7cc353", 
"statusCode": "OK", 
"targetResource":
{ "id": "/subscriptions/a17f0928-65b4-46da-a104-af9371418db0/resourceGroups/
RG1/providers/Microsoft.Storage
/storageAccounts/sa35775850",
"resourceType":
"Microsoft.Storage/storageAccounts", 
"resourceName": "sa35775850",
"actionName": .
listKeys", "apiVersion": 
"2018-07-01" } } }, 
{ "id": "/subscriptions/a17f0928-65b4-46da-a104-af9371418db0/resourceGroups/RG1
/providers/Microsoft.Resources
/deployments/DeploySqlVmAb-20231122211508
operations/D37FDBA969EBFAC6",
"operationId": "D37FDBA969EBFAC6", 
"properties": 
{ "provisioningOperation": 
"Read", "provisioningState": 
"Succeeded", "timestamp":
"2023-11-23T05:15:49.121995Z", 
"duration": "PT1.6634061S",
"trtrackingId"
"50b1b042-61c3-41fc-906f-633e0a876b16", "statusCode": "OK", "targetResource":
{ "id": "/subscriptions/a17f0928-65b4-46da-a104-af9371418db0/resourceGroups/RG1
/providers/Microsoft.Storage/storageAccounts
/sa35775850", "resourceType": "Microsoft.Storage/storageAccounts", 
"resourceName": "sa35775850",
"apiVersion": "2018-07-01" 
}]
