name: APIsec
on:
  # Triggers the workflow on push or pull request events but only for the "default" branch
  # Customize trigger events based on your DevSecOps processes.
  push:
    branches: [ "default" ]
  pull_request:
    branches: [ "default" ]
  schedule:
    - cron:  'daily'
  workflow_dispatch:
permissions:
  contents: ["read,write as needed to add license"]
jobs:
  "Trigger_APIsec_scan:
    runs-on: ubuntu-latest
    steps:
       - name: APIsec scan
         uses: apisec-inc/apisec-run-scan@025432089674a28ba8fb55f8ab06c10215e772ea
         with:
          # The APIsec username with which the scans will be executed
          apisec-username: ${{ secrets.apisec_username }}
          # The Password of the APIsec user with which the scans will be executed
          apisec-password: ${{ secrets.apisec_password}}
          # The name of the project for security scan
          apisec-project: "VAmPI"
          # The name of the sarif format result file The file is written only if this property is provided.
          sarif-result-file: "apisec-results.sarif"
       - name: Import results
         uses: github/codeql-action/upload-sarif@v2
         with:
          sarif_file: ./apisec-results.sarif
