name: Format Code

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Format Shell scripts using shfmt
      - name: Format Shell scripts
        run: |
          sudo apt-get install -y shfmt
          shfmt -w .

      # Format Ruby files using RuboCop
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # Adjust if needed

      - name: Install RuboCop
        run: gem install rubocop

      - name: Format Ruby files
        run: rubocop -A || true

      # Format JavaScript files using Prettier
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Adjust if needed

      - name: Install Prettier
        run: npm install --global prettier

      - name: Format JavaScript files
        run: prettier --write "**/*.js"

        version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

      name: Auto Fix Lint Issues

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install RuboCop
        run: gem install rubocop

      - name: Run RuboCop auto-correct
        run: rubocop -A

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ESLint
        run: npm install --global eslint

      - name: Run ESLint auto-fix
        run: eslint --fix "**/*.js" || true

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: automated lint fixes"
          branch: ${{ github.head_ref || github.ref_name }}
